### ISSUE TITLE
svg images in  build aren't visible

### ISSUE THREAD

**Issue by jaroslaw-filipiak** [tomik23/webpack-boilerplate#19]
Hi and thanks for good work - this boilderplate is awesome!
i have problem with handling svg images that's are inline in html template for example in html file: 

```html
 <img class="lazy" data-src="./../images/image.svg" alt="">
```
i don't use PUG , only html files so after 'yarn prod' i dont have img / only 404 file not found

**Comment by tomik23** [comment]
Thanks.

As for the problem, in `webpack.prod.js` line 55-56 comment out this part. It blocked svg from being copied to the build folder.

In the html image template you need to specify <img src="<%=require('../images/logo.svg')%>" alt=""> 
Because the paths between dev and prod are definitely different?

In the webpack.common.js file, change the rules for svg
` {
    test: /\.svg/,
    type: 'asset/resource',
    generator: {
      filename: 'images/[name][ext]',
    },
  },
`
I hope it will help. If not, let me know and it's best to put your example on the github.
Then I'll have a look and help.
